name = "spanish"
main = "src/index.js"
compatibility_date = "2026-08-02"

# حتماً شناسه حساب خود را در اینجا قرار دهید
account_id = "9902af4a69cdffc5a087b2da0a0a5a4d" 

[vars]
# Spanishtoken را از اینجا پاک کنید و با دستور زیر ست کنید:
# wrangler secret put Spanishtoken

[[d1_databases]]
binding = "DB"
database_name = "spanish-bot-db"
database_id = "Df8d82a0-b568-4641-bce8-334518fd6977"
