name = "spanish"
main = "src/index.js"
compatibility_date = "2026-08-02"

[vars]
spanishtoken = "8839168525:AAFKVI5cFYTiOLuhIMUQtEzBhDG5n24ykU0"

[[d1_databases]]
binding = "DB"
database_name = "spanish-bot-db"
database_id = "Df8d82a0-b568-4641-bce8-334518fd6977"
